language: java

jdk:
- oraclejdk8

install: mvn clean install

cache:
  directories:
  - $HOME/.m2

before_install:
  - echo "MAVEN_OPTS='-Xmx2g'" > ~/.mavenrc

script: mvn package appassembler:assemble